"""V3:共享测试工厂 —— 构造全字段合法的 MaterialProfile / Bitable 行 / 附件文本。

默认值对应一个 L1002 @ BBL P2S 的 BambuStudio 档案;各测试用 override
改个别字段,避免每个用例手写 13 个必填值。
"""

import json

from material_worker import fields
from material_worker.domain.profile import FIELD_SCHEMA, MaterialProfile

DEFAULTS = {
    "pi_code": "L1002",
    "printer_model": "BBL P2S",
    "slicer": "BambuStudio",
    "pm_method_version": "v1",
    "inherits": "Panchroma PLA",
    "textured_plate_temp": 55,
    "nozzle_temperature": 220,
    "fan_cooling_layer_time": 20,
    "fan_max_speed": 60,
    "fan_min_speed": 0,
    "slow_down_layer_time": 4,
    "filament_flow_ratio": 0.95,
    "filament_max_volumetric_speed": 18,
}

#: 默认身份对应的仓库内路径(V3-P4 布局)
DEFAULT_IDENTITY = "L1002@BBL P2S"
DEFAULT_REPO_PATH = (
    "preset/L1002/BBL/P2S/BambuStudio/L1002@BBL P2S.json"
)
DEFAULT_BRANCH = "material/L1002@BBL_P2S_BambuStudio"

#: 默认身份的提交人 / 提交时间(PR 正文与 commit message 里出现)
DEFAULT_SUBMITTER = "张三"
DEFAULT_SUBMIT_TIME = "2026-09-11 10:23"


def make_profile(**overrides) -> MaterialProfile:
    kwargs = dict(DEFAULTS)
    kwargs.update(overrides)
    return MaterialProfile(**kwargs)


def row_fields(**overrides) -> dict:
    """Bitable 行字段快照:每个 canonical 列一个默认合法值。

    可选列(线材密度/玻璃化温度/回抽距离/压力提前)默认留空;
    状态/PR URL/提交人等由调用方另补。
    """
    data = {}
    for f in FIELD_SCHEMA:
        if f.key in DEFAULTS:
            data[f.column] = DEFAULTS[f.key]
    data.update(overrides)
    return data


def profile_attachment_json(**overrides) -> str:
    """合法附件 JSON(canonical 英文 key):默认必填项 + 覆盖项。

    `key=None` 表示从附件里删掉该键(用于验证「缺键不再报错」)。
    """
    payload: dict = {}
    for f in FIELD_SCHEMA:
        if f.key in DEFAULTS:
            payload[f.key] = DEFAULTS[f.key]
    for key, value in overrides.items():
        if value is None:
            payload.pop(key, None)
        else:
            payload[key] = value
    return json.dumps(payload)


def prusa_ini(**overrides) -> str:
    """一份最小的 PrusaSlicer filament `.ini`(扁平 key = value)。"""
    values = {
        "temperature": 200,
        "first_layer_temperature": 210,
        "bed_temperature": 60,
        "first_layer_bed_temperature": 60,
        "extrusion_multiplier": 0.99,
        "filament_max_volumetric_speed": 12,
        "fan_below_layer_time": 100,
        "slowdown_below_layer_time": 15,
        "max_fan_speed": 100,
        "min_fan_speed": 100,
        "filament_density": 1.29,
        "filament_retract_length": "nil",
        "inherits": "Prusament PLA @COREONE",
    }
    values.update(overrides)
    lines = ["# generated by PrusaSlicer 2.9.4 on 2026-04-13 at 02:19:49 UTC"]
    lines.extend(f"{k} = {v}" for k, v in values.items())
    return "\n".join(lines) + "\n"


def attachment_item(name: str, token: str = "tok-1"):
    """Bitable 附件单元格项(适配层 AttachmentItem)。"""
    from material_worker.adapters.bitable import AttachmentItem

    return AttachmentItem(file_token=token, name=name)


def attachment_cell(*names: str) -> list[dict]:
    """Bitable 附件列的原始单元格形态(list[{file_token, name}])。"""
    return [
        {"file_token": f"tok-{i}", "name": name}
        for i, name in enumerate(names, start=1)
    ]


__all__ = [
    "DEFAULTS",
    "DEFAULT_IDENTITY",
    "DEFAULT_REPO_PATH",
    "DEFAULT_BRANCH",
    "DEFAULT_SUBMITTER",
    "DEFAULT_SUBMIT_TIME",
    "make_profile",
    "row_fields",
    "profile_attachment_json",
    "prusa_ini",
    "attachment_item",
    "attachment_cell",
    "fields",
    "FIELD_SCHEMA",
    "MaterialProfile",
]
