"""PrusaSlicer `.ini` 预设的**导入**映射(V3-P6 —— worker 里唯一的切片器知识)。

方向只有「文件 -> 表格」:用户上传一个 PrusaSlicer 导出的 filament 预设,
worker 按本表反查回表格列并「只填空」反写。

输出方向 worker 完全不涉及 —— `preset-db` 里一律写基础数据 JSON,
`.ini` 生成、键映射、字符串数组化、`_initial_layer` 伴随键等全部由
构建脚本负责(V3 决策 10/8)。

真实 `.ini` 形态(见 Polymaker-Preset 实况):扁平 `key = value`,
无 section,首行 `# generated by PrusaSlicer …`,数值键大多为裸标量,
`nil` 表示「跟随打印机设置」。
"""

from __future__ import annotations

# PrusaSlicer key -> canonical key(与 BambuStudio 系同一套 canonical 名)。
# 仅列出有对等键的;其余 Prusa 键一律忽略。
PRUSA_IMPORT_MAP: dict[str, str] = {
    "temperature": "nozzle_temperature",
    "bed_temperature": "textured_plate_temp",
    "extrusion_multiplier": "filament_flow_ratio",
    "filament_max_volumetric_speed": "filament_max_volumetric_speed",
    "fan_below_layer_time": "fan_cooling_layer_time",
    "slowdown_below_layer_time": "slow_down_layer_time",
    "max_fan_speed": "fan_max_speed",
    "min_fan_speed": "fan_min_speed",
    "filament_density": "filament_density",
    "filament_retract_length": "filament_retraction_length",
    "inherits": "inherits",
}

# 首层温度回退链:真实文件里 `temperature`(稳态)与
# `first_layer_temperature`(首层)常常不等(如 200 / 210),而表格只有
# 一个「喷嘴温度」列 —— 优先取稳态值,缺失时才回退首层值。热床同理。
_PRUSA_FALLBACK_CHAINS: dict[str, tuple[str, ...]] = {
    "nozzle_temperature": ("temperature", "first_layer_temperature"),
    "textured_plate_temp": ("bed_temperature", "first_layer_bed_temperature"),
}

#: 这些 Prusa 键在表格里**没有**对等列,解析时直接忽略:
#: 玻璃化温度(无对等键)、压力提前(Prusa 写在 start_filament_gcode 的
#: M572 里,不是 filament 级标量键)。
PRUSA_IGNORED_KEYS: frozenset[str] = frozenset(
    {"temperature_vitrification", "pressure_advance"}
)


def parse_prusa_ini(text: str) -> dict[str, str]:
    """扁平 `key = value` 文本 -> {key: value}(首见优先,忽略注释/空行)。

    值两侧的引号会被剥掉;`nil`/空值保留原样,由调用方按「跳过」处理
    (不在这里丢弃,以便回退链判断「该键存在但无值」)。
    """
    values: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith(";"):
            continue
        if "=" not in stripped:
            continue
        key, _, raw = stripped.partition("=")
        key = key.strip()
        if not key or key in values:
            continue  # 首见优先:同一 key 重复出现时取第一次
        value = raw.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        values[key] = value
    return values


def extract_prusa_values(text: str) -> dict[str, str]:
    """`.ini` 文本 -> {canonical key: 原始字符串值}(仅含认得的键)。

    不做数值解析、不过滤 `nil` —— 由 attachment_import 统一按
    FIELD_SCHEMA 的类型与「取不到就跳过」规则处理。
    """
    raw = parse_prusa_ini(text)
    out: dict[str, str] = {}
    for canonical, chain in _PRUSA_FALLBACK_CHAINS.items():
        for prusa_key in chain:
            if prusa_key in raw:
                out[canonical] = raw[prusa_key]
                break
    for prusa_key, canonical in PRUSA_IMPORT_MAP.items():
        if canonical in _PRUSA_FALLBACK_CHAINS:
            continue  # 已由回退链处理
        if prusa_key in raw:
            out[canonical] = raw[prusa_key]
    return out
